export default [
  {
    location: 'Astoria, Queens',
    title: 'Arepas Cafe',
    description: 'Bianca loves these arepas so much, she waited outside with friends for 45 minutes during a polar vortex just to secure a table.',
    image: 'arepas-cafe',
    link: 'https://www.theinfatuation.com/new-york/reviews/arepas-cafe',
  },
  {
    location: 'Brooklyn',
    title: 'Prospect Park',
    description: 'You will find Fernando playing soccer in this park most weekends. Best place for a hike and a picnic.',
    image: 'prospect-park',
    link: 'https://www.prospectpark.org/',
  },
  {
    location: 'Dumbo, Brooklyn',
    title: "Juliana's Pizza",
    description: "If you ask Fernando, this might be the best pizza in NYC. It's also located near the beautiful Brooklyn Bridge Park.",
    image: 'julianas',
    link: 'https://julianaspizza.com/',
  },
  {
    location: 'Greenpoint, Brooklyn',
    title: 'El Born',
    description: 'We love the tapas and cocktails here. It’s also where we shared our first kiss.',
    image: 'el-born',
    link: 'https://www.elbornnyc.com/',
  },
  {
    location: 'South Williamsburg, Brooklyn',
    title: "Duff's",
    description: 'The longest running metal party on the planet.',
    image: 'duffs',
    link: 'http://duffsbrooklyn.com/',
  },
  {
    location: 'Upper West Side, Manhattan',
    title: "American Museum of Natural History",
    description: "This museum is Bianca’s favorite place in the city, where she goes to reconnect with her inner child.",
    image: 'american-museum-of-natural-history',
    link: 'https://www.amnh.org/',
  },
  {
    location: 'Hudson Yards, Manhattan',
    title: 'Mercado Little Spain',
    description: 'An amazing Spanish food market. For a spiritual experience, try their tarta de queso with a Pedro Ximenez sherry.',
    image: 'mercado-little-spain',
    link: 'https://www.littlespain.com/',
  },
  {
    location: 'Park Slope, Brooklyn',
    title: 'Bogota Latin Bistro',
    description: "When Fernando craves his people's food, this is where we feast. Come hungry, the portions are masive!",
    image: 'bogota-latin-bistro',
    link: 'https://www.bogotabistro.com/',
  },
  {
    location: 'Park Slope, Brooklyn',
    title: 'Nitehawk Cinema',
    description: "We love watching movies at this indie dine-in theater. Go for the vibes and cleverly themed menus.",
    image: 'nitehawk-cinema',
    link: 'https://nitehawkcinema.com/prospectpark/',
  },
];