export default [
  {
    location: 'Astoria, Queens',
    title: 'Arepas Cafe',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    image: 'arepas-cafe',
    link: 'https://www.theinfatuation.com/new-york/reviews/arepas-cafe',
  },
  {
    location: 'Brooklyn',
    title: 'Prospect Park',
    description: 'You will find Fernando playing soccer in this park most weekends. Best place for a hike and a picnic.',
    image: 'prospect-park',
    link: 'https://www.prospectpark.org/',
  },
  {
    location: 'Dumbo, Brooklyn',
    title: "Juliana's Pizza",
    description: 'Best Pie in NYC according to Fernando. Located near beautiful Brooklyn Bridge Park.',
    image: 'julianas',
    link: 'https://julianaspizza.com/',
  },
  {
    location: 'Greenpoint, Brooklyn',
    title: 'El Born',
    description: 'Great tapas',
    image: 'el-born',
    link: 'https://www.elbornnyc.com/',
  },
  {
    location: 'South Williamsburg, Brooklyn',
    title: "Duff's",
    description: 'The longest running metal party on the planet.',
    image: 'duffs',
    link: 'http://duffsbrooklyn.com/',
  },
  {
    location: 'Upper West Side, Manhattan',
    title: "American Museum of Natural History",
    description: "Bianca's favorite museum - dinosaurs!",
    image: 'american-museum-of-natural-history',
    link: 'https://www.amnh.org/',
  },
  {
    location: 'Hudson Yards, Manhattan',
    title: 'Mercado Little Spain',
    description: 'Torta de queso y Pedro Ximenez!',
    image: 'mercado-little-spain',
    link: 'https://www.littlespain.com/',
  },
  {
    location: 'Park Slope, Brooklyn',
    title: 'Bogota Latin Bistro',
    description: 'Best Colombian food in Brooklyn',
    image: 'bogota-latin-bistro',
    link: 'https://www.bogotabistro.com/',
  },
  {
    location: 'Park Slope, Brooklyn',
    title: 'Nitehawk Cinema',
    description: 'Dinner and a movie!',
    image: 'nitehawk-cinema',
    link: 'https://nitehawkcinema.com/prospectpark/',
  },
  {
    location: 'East Village, Manhattan',
    title: 'Cha Cha Matcha',
    description: 'Matcha!',
    image: 'cha-cha-matcha',
    link: 'https://chachamatcha.com/',
  },
];